### ISSUE TITLE
TestFairy Deploy fails

### ISSUE THREAD

**Issue by parkerjohn** [bitrise-io/steps-testfairy-deploy#15]
I have tried with the Private Cloud Endpoint field empty and with the TestFairy URL mentioned in the error, I get the exact same failure message either way:

/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise554855214/step_src/testfairy-upload-ios.sh: line 59: ![: command not found
Uploading /Users/vagrant/deploy/Toon.ipa to TestFairy.. 
## Deploy Failed

Failed to upload the build due to the following error:
Server moved, please send upload requests to https://quby.testfairy-eu.com

**Comment by imrekel** [comment]
hi @parkerjohn, is this issue still present for you? There is no reference to the URL you posted (`quby.testfairy-eu.com`) in the official Testfairy docs: https://docs.testfairy.com/API/Upload_API.html
Anyhow, we have just released a new version of the step and switched to `upload.testfairy.com` (https://github.com/bitrise-steplib/steps-testfairy-deploy/releases/tag/2.3.1). Could you give it a try?

**Comment by parkerjohn** [comment]
That is our TestFairy private cloud endpoint, it works for curl uploads. This feature was requested in the step github by others.

My bash step is working, I will probably stick with that for now.

Thanks

John

Sent from IBM Verse


   Imre Kelényi --- Re: [bitrise-steplib/steps-testfairy-deploy] TestFairy Deploy fails (#15) --- 
    From:"Imre Kelényi" <notifications@github.com>To:"bitrise-steplib/steps-testfairy-deploy" <steps-testfairy-deploy@noreply.github.com>Cc:"John Parker" <jparker@farcomm.com>, "Mention" <mention@noreply.github.com>Date:Thu, 15 Oct 2020 03:05Subject:Re: [bitrise-steplib/steps-testfairy-deploy] TestFairy Deploy fails (#15)
  
  hi @parkerjohn, is this issue still present for you? There is no reference to the URL you posted (quby.testfairy-eu.com) in the official Testfairy docs: https://docs.testfairy.com/API/Upload_API.html
  Anyhow, we have just released a new version of the step and switched to upload.testfairy.com. Could you give it a try? —

**Comment by imrekel** [comment]
Oh, I see now. There is actually a syntax error in our scripts for setting the private cloud endpoint. Fixing it asap, will let you know when it's released.

**Comment by imrekel** [comment]
Error fixed in 2.3.2 https://github.com/bitrise-steplib/steps-testfairy-deploy/releases/tag/2.3.2
