### ISSUE TITLE
Generate download URL output

### ISSUE THREAD

**Issue by guitcastro** [bitrise-io/steps-testfairy-deploy#4]
Generate the url output variable with success like `${BITRISE_BUILD_URL}`, to be used in others workflows like Slack.

What you guys think ?

**Comment by viktorbenei** [comment]
I think it's a really good idea 😊
Do you have time to implement it?

**Comment by guitcastro** [comment]
Yeap, you just have to point me the right direction because I getting starting with bitrise this week.

Looking at the steps-bitrise-ios-deploy repository I guess I just have to:
1. add `envman add --key BITRISE_PUBLIC_INSTALL_PAGE_URL --value $URL` at the end of `testfairy-upload-ios.sh`
2. register the output at the `/step.yml`

What do you think?

**Comment by viktorbenei** [comment]
You're right @guitcastro , that's all what you need. `envman` is used to manage Environment Variables between separate Steps (if you would need more complex examples, like exporting a multi line value as ENV, you can find those at `envman`'s repo: https://github.com/bitrise-io/envman ); and you should list these (the ENVs you expose with `envman`) in the `step.yml` file.

**Comment by guitcastro** [comment]
@viktorbenei Cool! On Tomorrow I'm gonna try to implement it ;)

**Comment by viktorbenei** [comment]
Ping us if you need any help / info 😉

**Comment by guitcastro** [comment]
Ok, I modify the script and run it locally.

How can I test with the environment variable is set? 
A simple `echo $TESTFAIRY_PUBLIC_INSTALL_PAGE_URL` did not work (or the script did not worked). =/

**Comment by guitcastro** [comment]
Never mind, looking at the steps-hockeyapp-deploy I found out:

```
- script:
        inputs:
        - content: |-
            #!/bin/bash
            echo "TESTFAIRY_PUBLIC_INSTALL_PAGE_URL: ${TESTFAIRY_PUBLIC_INSTALL_PAGE_URL}"
```

**Comment by guitcastro** [comment]
#5

**Comment by viktorbenei** [comment]
Closing the issue as the PR implemented the fix - just forgot to close it here.

Thanks again @guitcastro for the PR! ;)
