### ISSUE TITLE
Mark API key and Test Groups to expand

### ISSUE THREAD

**Issue by dkpalmer** [bitrise-io/steps-testfairy-deploy#6]
Similar to the [Android](https://github.com/bitrise-steplib/steps-testfairy-deploy-android/blob/master/step.yml) version, we'd like to provide the api_key and tester_groups as variables that can expand.

Looks like just need to nix `is_expand: false` ? I'm happy to put up a PR if that's the case, unless you'd prefer to make the change.

**Comment by viktorbenei** [comment]
Hi @dkpalmer, 

You can change the is_expand flag in your Bitrise.yml, you can find the related docs at http://devcenter.bitrise.io/getting-started/manage-your-bitrise-workflow/#environment-variable-replace-mode

Whether we should change the default here, that's another question.. I'll bring this up for a discussion with the team. I'd say in this case enabling it by default would be the right choice, but that can cause issues if the value might include the $ character if the value is provided directly, not through an env var. 

In any case, thanks for pointing this out, I agree with you, so if you have the time feel free to create a PR, but I'll have to discuss this with the team.
